name: Deploy Hugo site to FTP

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.126.1'   # mets ta version si différente
          extended: true

      - name: Build
        env:
          HUGO_ENV: production
        run: |
          hugo --minify --cleanDestinationDir
          echo "---- robots.txt ----"
          if [ -f public/robots.txt ]; then cat public/robots.txt; else echo "robots.txt NOT FOUND"; fi

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}           # ou FTP_USERNAME selon tes secrets
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /www/leo-nc.info/               # ← adapte au chemin réel
          dangerous-clean-slate: true
          log-level: verbose
