name: Deploy to FTP

on:
  push:
    branches:
      - main  # Déclenchement lorsque tu pousses sur la branche "main"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Étape 3 : Construire le site Hugo
      - name: Build Hugo site
        run: hugo

      # Étape 4 : Déployer via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
